# This file is generated by Vest!
# Do not modify!
extends "res://addons/vest/_generated-mixins/4-96ae432f.gd"



func _init():
	super()

	on_case_finish.connect(func(case):
		var messages := Vest._get_messages()
		if not messages.is_empty():
			_result.data["messages"] = messages
		Vest._clear_messages()
	)
