name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.2.2
          use-dotnet: false
          include-templates: false
      - name: Verify setup
        run: godot --version
      - name: Run tests
        run: |
          godot --headless --import .
          godot --headless -s "addons/vest/cli/vest-cli.gd" \
                --vest-report-format tap --vest-report-file "vest.log" \
                --vest-glob "res://test/*.test.gd"
          if grep "not ok" "vest.log"; then
            exit 1
          fi
